/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_gia_hai_long.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CauHoi service. Represents a row in the &quot;alpha_dghl_cauhoi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alpha.portlet.danh_gia_hai_long.model.impl.CauHoiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alpha.portlet.danh_gia_hai_long.model.impl.CauHoiImpl}.
 * </p>
 *
 * @author darkn
 * @see CauHoi
 * @see com.alpha.portlet.danh_gia_hai_long.model.impl.CauHoiImpl
 * @see com.alpha.portlet.danh_gia_hai_long.model.impl.CauHoiModelImpl
 * @generated
 */
public interface CauHoiModel extends BaseModel<CauHoi>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cau hoi model instance should use the {@link CauHoi} interface instead.
	 */

	/**
	 * Returns the primary key of this cau hoi.
	 *
	 * @return the primary key of this cau hoi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cau hoi.
	 *
	 * @param primaryKey the primary key of this cau hoi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cau hoi ID of this cau hoi.
	 *
	 * @return the cau hoi ID of this cau hoi
	 */
	public long getCauHoiId();

	/**
	 * Sets the cau hoi ID of this cau hoi.
	 *
	 * @param cauHoiId the cau hoi ID of this cau hoi
	 */
	public void setCauHoiId(long cauHoiId);

	/**
	 * Returns the group ID of this cau hoi.
	 *
	 * @return the group ID of this cau hoi
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this cau hoi.
	 *
	 * @param groupId the group ID of this cau hoi
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this cau hoi.
	 *
	 * @return the company ID of this cau hoi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cau hoi.
	 *
	 * @param companyId the company ID of this cau hoi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this cau hoi.
	 *
	 * @return the user ID of this cau hoi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this cau hoi.
	 *
	 * @param userId the user ID of this cau hoi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cau hoi.
	 *
	 * @return the user uuid of this cau hoi
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this cau hoi.
	 *
	 * @param userUuid the user uuid of this cau hoi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cau hoi.
	 *
	 * @return the user name of this cau hoi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this cau hoi.
	 *
	 * @param userName the user name of this cau hoi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cau hoi.
	 *
	 * @return the create date of this cau hoi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cau hoi.
	 *
	 * @param createDate the create date of this cau hoi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cau hoi.
	 *
	 * @return the modified date of this cau hoi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cau hoi.
	 *
	 * @param modifiedDate the modified date of this cau hoi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this cau hoi.
	 *
	 * @return the ten of this cau hoi
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this cau hoi.
	 *
	 * @param ten the ten of this cau hoi
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma of this cau hoi.
	 *
	 * @return the ma of this cau hoi
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this cau hoi.
	 *
	 * @param ma the ma of this cau hoi
	 */
	public void setMa(String ma);

	/**
	 * Returns the mo ta of this cau hoi.
	 *
	 * @return the mo ta of this cau hoi
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this cau hoi.
	 *
	 * @param moTa the mo ta of this cau hoi
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the hoat dong of this cau hoi.
	 *
	 * @return the hoat dong of this cau hoi
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this cau hoi is hoat dong.
	 *
	 * @return <code>true</code> if this cau hoi is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this cau hoi is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this cau hoi
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the do uu tien of this cau hoi.
	 *
	 * @return the do uu tien of this cau hoi
	 */
	public int getDoUuTien();

	/**
	 * Sets the do uu tien of this cau hoi.
	 *
	 * @param doUuTien the do uu tien of this cau hoi
	 */
	public void setDoUuTien(int doUuTien);

	/**
	 * Returns the bo cau hoi of this cau hoi.
	 *
	 * @return the bo cau hoi of this cau hoi
	 */
	public int getBoCauHoi();

	/**
	 * Sets the bo cau hoi of this cau hoi.
	 *
	 * @param boCauHoi the bo cau hoi of this cau hoi
	 */
	public void setBoCauHoi(int boCauHoi);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.alpha.portlet.danh_gia_hai_long.model.CauHoi cauHoi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alpha.portlet.danh_gia_hai_long.model.CauHoi> toCacheModel();

	@Override
	public com.alpha.portlet.danh_gia_hai_long.model.CauHoi toEscapedModel();

	@Override
	public com.alpha.portlet.danh_gia_hai_long.model.CauHoi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}