/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_gia_hai_long.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DanhGiaHaiLong service. Represents a row in the &quot;alpha_dghl_danhgiahailong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alpha.portlet.danh_gia_hai_long.model.impl.DanhGiaHaiLongModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alpha.portlet.danh_gia_hai_long.model.impl.DanhGiaHaiLongImpl}.
 * </p>
 *
 * @author darkn
 * @see DanhGiaHaiLong
 * @see com.alpha.portlet.danh_gia_hai_long.model.impl.DanhGiaHaiLongImpl
 * @see com.alpha.portlet.danh_gia_hai_long.model.impl.DanhGiaHaiLongModelImpl
 * @generated
 */
public interface DanhGiaHaiLongModel extends BaseModel<DanhGiaHaiLong>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a danh gia hai long model instance should use the {@link DanhGiaHaiLong} interface instead.
	 */

	/**
	 * Returns the primary key of this danh gia hai long.
	 *
	 * @return the primary key of this danh gia hai long
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this danh gia hai long.
	 *
	 * @param primaryKey the primary key of this danh gia hai long
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the danh gia hai long ID of this danh gia hai long.
	 *
	 * @return the danh gia hai long ID of this danh gia hai long
	 */
	public long getDanhGiaHaiLongId();

	/**
	 * Sets the danh gia hai long ID of this danh gia hai long.
	 *
	 * @param danhGiaHaiLongId the danh gia hai long ID of this danh gia hai long
	 */
	public void setDanhGiaHaiLongId(long danhGiaHaiLongId);

	/**
	 * Returns the group ID of this danh gia hai long.
	 *
	 * @return the group ID of this danh gia hai long
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this danh gia hai long.
	 *
	 * @param groupId the group ID of this danh gia hai long
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this danh gia hai long.
	 *
	 * @return the company ID of this danh gia hai long
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this danh gia hai long.
	 *
	 * @param companyId the company ID of this danh gia hai long
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this danh gia hai long.
	 *
	 * @return the user ID of this danh gia hai long
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this danh gia hai long.
	 *
	 * @param userId the user ID of this danh gia hai long
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this danh gia hai long.
	 *
	 * @return the user uuid of this danh gia hai long
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this danh gia hai long.
	 *
	 * @param userUuid the user uuid of this danh gia hai long
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this danh gia hai long.
	 *
	 * @return the user name of this danh gia hai long
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this danh gia hai long.
	 *
	 * @param userName the user name of this danh gia hai long
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this danh gia hai long.
	 *
	 * @return the create date of this danh gia hai long
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this danh gia hai long.
	 *
	 * @param createDate the create date of this danh gia hai long
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this danh gia hai long.
	 *
	 * @return the modified date of this danh gia hai long
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this danh gia hai long.
	 *
	 * @param modifiedDate the modified date of this danh gia hai long
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the resource code of this danh gia hai long.
	 *
	 * @return the resource code of this danh gia hai long
	 */
	public long getResourceCode();

	/**
	 * Sets the resource code of this danh gia hai long.
	 *
	 * @param resourceCode the resource code of this danh gia hai long
	 */
	public void setResourceCode(long resourceCode);

	/**
	 * Returns the resource p k of this danh gia hai long.
	 *
	 * @return the resource p k of this danh gia hai long
	 */
	public long getResourcePK();

	/**
	 * Sets the resource p k of this danh gia hai long.
	 *
	 * @param resourcePK the resource p k of this danh gia hai long
	 */
	public void setResourcePK(long resourcePK);

	/**
	 * Returns the cau hoi ID of this danh gia hai long.
	 *
	 * @return the cau hoi ID of this danh gia hai long
	 */
	public long getCauHoiId();

	/**
	 * Sets the cau hoi ID of this danh gia hai long.
	 *
	 * @param cauHoiId the cau hoi ID of this danh gia hai long
	 */
	public void setCauHoiId(long cauHoiId);

	/**
	 * Returns the tra loi ID of this danh gia hai long.
	 *
	 * @return the tra loi ID of this danh gia hai long
	 */
	public long getTraLoiId();

	/**
	 * Sets the tra loi ID of this danh gia hai long.
	 *
	 * @param traLoiId the tra loi ID of this danh gia hai long
	 */
	public void setTraLoiId(long traLoiId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong danhGiaHaiLong);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong> toCacheModel();

	@Override
	public com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong toEscapedModel();

	@Override
	public com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}