/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_gia_hai_long.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TraLoi service. Represents a row in the &quot;alpha_dghl_traloi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alpha.portlet.danh_gia_hai_long.model.impl.TraLoiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alpha.portlet.danh_gia_hai_long.model.impl.TraLoiImpl}.
 * </p>
 *
 * @author darkn
 * @see TraLoi
 * @see com.alpha.portlet.danh_gia_hai_long.model.impl.TraLoiImpl
 * @see com.alpha.portlet.danh_gia_hai_long.model.impl.TraLoiModelImpl
 * @generated
 */
public interface TraLoiModel extends BaseModel<TraLoi>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tra loi model instance should use the {@link TraLoi} interface instead.
	 */

	/**
	 * Returns the primary key of this tra loi.
	 *
	 * @return the primary key of this tra loi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tra loi.
	 *
	 * @param primaryKey the primary key of this tra loi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tra loi ID of this tra loi.
	 *
	 * @return the tra loi ID of this tra loi
	 */
	public long getTraLoiId();

	/**
	 * Sets the tra loi ID of this tra loi.
	 *
	 * @param traLoiId the tra loi ID of this tra loi
	 */
	public void setTraLoiId(long traLoiId);

	/**
	 * Returns the group ID of this tra loi.
	 *
	 * @return the group ID of this tra loi
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tra loi.
	 *
	 * @param groupId the group ID of this tra loi
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tra loi.
	 *
	 * @return the company ID of this tra loi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tra loi.
	 *
	 * @param companyId the company ID of this tra loi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tra loi.
	 *
	 * @return the user ID of this tra loi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tra loi.
	 *
	 * @param userId the user ID of this tra loi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tra loi.
	 *
	 * @return the user uuid of this tra loi
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tra loi.
	 *
	 * @param userUuid the user uuid of this tra loi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tra loi.
	 *
	 * @return the user name of this tra loi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tra loi.
	 *
	 * @param userName the user name of this tra loi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tra loi.
	 *
	 * @return the create date of this tra loi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tra loi.
	 *
	 * @param createDate the create date of this tra loi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tra loi.
	 *
	 * @return the modified date of this tra loi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tra loi.
	 *
	 * @param modifiedDate the modified date of this tra loi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the cau hoi ID of this tra loi.
	 *
	 * @return the cau hoi ID of this tra loi
	 */
	public long getCauHoiId();

	/**
	 * Sets the cau hoi ID of this tra loi.
	 *
	 * @param cauHoiId the cau hoi ID of this tra loi
	 */
	public void setCauHoiId(long cauHoiId);

	/**
	 * Returns the noi dung of this tra loi.
	 *
	 * @return the noi dung of this tra loi
	 */
	@AutoEscape
	public String getNoiDung();

	/**
	 * Sets the noi dung of this tra loi.
	 *
	 * @param noiDung the noi dung of this tra loi
	 */
	public void setNoiDung(String noiDung);

	/**
	 * Returns the muc do hai long of this tra loi.
	 *
	 * @return the muc do hai long of this tra loi
	 */
	public int getMucDoHaiLong();

	/**
	 * Sets the muc do hai long of this tra loi.
	 *
	 * @param mucDoHaiLong the muc do hai long of this tra loi
	 */
	public void setMucDoHaiLong(int mucDoHaiLong);

	/**
	 * Returns the diem of this tra loi.
	 *
	 * @return the diem of this tra loi
	 */
	public int getDiem();

	/**
	 * Sets the diem of this tra loi.
	 *
	 * @param diem the diem of this tra loi
	 */
	public void setDiem(int diem);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.alpha.portlet.danh_gia_hai_long.model.TraLoi traLoi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alpha.portlet.danh_gia_hai_long.model.TraLoi> toCacheModel();

	@Override
	public com.alpha.portlet.danh_gia_hai_long.model.TraLoi toEscapedModel();

	@Override
	public com.alpha.portlet.danh_gia_hai_long.model.TraLoi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}