/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_gia_hai_long.model.impl;

import com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong;
import com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the DanhGiaHaiLong service. Represents a row in the &quot;alpha_dghl_danhgiahailong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhGiaHaiLongImpl}.
 * </p>
 *
 * @author darkn
 * @see DanhGiaHaiLongImpl
 * @see com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong
 * @generated
 */
public abstract class DanhGiaHaiLongBaseImpl extends DanhGiaHaiLongModelImpl
	implements DanhGiaHaiLong {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh gia hai long model instance should use the {@link DanhGiaHaiLong} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			DanhGiaHaiLongLocalServiceUtil.addDanhGiaHaiLong(this);
		}
		else {
			DanhGiaHaiLongLocalServiceUtil.updateDanhGiaHaiLong(this);
		}
	}
}