/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_gia_hai_long.model.impl;

import com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong;
import com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLongModel;
import com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLongSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DanhGiaHaiLong service. Represents a row in the &quot;alpha_dghl_danhgiahailong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLongModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhGiaHaiLongImpl}.
 * </p>
 *
 * @author darkn
 * @see DanhGiaHaiLongImpl
 * @see com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong
 * @see com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLongModel
 * @generated
 */
@JSON(strict = true)
public class DanhGiaHaiLongModelImpl extends BaseModelImpl<DanhGiaHaiLong>
	implements DanhGiaHaiLongModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh gia hai long model instance should use the {@link com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong} interface instead.
	 */
	public static final String TABLE_NAME = "alpha_dghl_danhgiahailong";
	public static final Object[][] TABLE_COLUMNS = {
			{ "danhGiaHaiLongId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "resourceCode", Types.BIGINT },
			{ "resourcePK", Types.BIGINT },
			{ "cauHoiId", Types.BIGINT },
			{ "traLoiId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table alpha_dghl_danhgiahailong (danhGiaHaiLongId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,resourceCode LONG,resourcePK LONG,cauHoiId LONG,traLoiId LONG)";
	public static final String TABLE_SQL_DROP = "drop table alpha_dghl_danhgiahailong";
	public static final String ORDER_BY_JPQL = " ORDER BY danhGiaHaiLong.danhGiaHaiLongId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY alpha_dghl_danhgiahailong.danhGiaHaiLongId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long RESOURCECODE_COLUMN_BITMASK = 2L;
	public static long RESOURCEPK_COLUMN_BITMASK = 4L;
	public static long DANHGIAHAILONGID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DanhGiaHaiLong toModel(DanhGiaHaiLongSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DanhGiaHaiLong model = new DanhGiaHaiLongImpl();

		model.setDanhGiaHaiLongId(soapModel.getDanhGiaHaiLongId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setResourceCode(soapModel.getResourceCode());
		model.setResourcePK(soapModel.getResourcePK());
		model.setCauHoiId(soapModel.getCauHoiId());
		model.setTraLoiId(soapModel.getTraLoiId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DanhGiaHaiLong> toModels(DanhGiaHaiLongSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DanhGiaHaiLong> models = new ArrayList<DanhGiaHaiLong>(soapModels.length);

		for (DanhGiaHaiLongSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong"));

	public DanhGiaHaiLongModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _danhGiaHaiLongId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDanhGiaHaiLongId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _danhGiaHaiLongId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DanhGiaHaiLong.class;
	}

	@Override
	public String getModelClassName() {
		return DanhGiaHaiLong.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("danhGiaHaiLongId", getDanhGiaHaiLongId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("resourceCode", getResourceCode());
		attributes.put("resourcePK", getResourcePK());
		attributes.put("cauHoiId", getCauHoiId());
		attributes.put("traLoiId", getTraLoiId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long danhGiaHaiLongId = (Long)attributes.get("danhGiaHaiLongId");

		if (danhGiaHaiLongId != null) {
			setDanhGiaHaiLongId(danhGiaHaiLongId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long resourceCode = (Long)attributes.get("resourceCode");

		if (resourceCode != null) {
			setResourceCode(resourceCode);
		}

		Long resourcePK = (Long)attributes.get("resourcePK");

		if (resourcePK != null) {
			setResourcePK(resourcePK);
		}

		Long cauHoiId = (Long)attributes.get("cauHoiId");

		if (cauHoiId != null) {
			setCauHoiId(cauHoiId);
		}

		Long traLoiId = (Long)attributes.get("traLoiId");

		if (traLoiId != null) {
			setTraLoiId(traLoiId);
		}
	}

	@JSON
	@Override
	public long getDanhGiaHaiLongId() {
		return _danhGiaHaiLongId;
	}

	@Override
	public void setDanhGiaHaiLongId(long danhGiaHaiLongId) {
		_columnBitmask = -1L;

		_danhGiaHaiLongId = danhGiaHaiLongId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getResourceCode() {
		return _resourceCode;
	}

	@Override
	public void setResourceCode(long resourceCode) {
		_columnBitmask |= RESOURCECODE_COLUMN_BITMASK;

		if (!_setOriginalResourceCode) {
			_setOriginalResourceCode = true;

			_originalResourceCode = _resourceCode;
		}

		_resourceCode = resourceCode;
	}

	public long getOriginalResourceCode() {
		return _originalResourceCode;
	}

	@JSON
	@Override
	public long getResourcePK() {
		return _resourcePK;
	}

	@Override
	public void setResourcePK(long resourcePK) {
		_columnBitmask |= RESOURCEPK_COLUMN_BITMASK;

		if (!_setOriginalResourcePK) {
			_setOriginalResourcePK = true;

			_originalResourcePK = _resourcePK;
		}

		_resourcePK = resourcePK;
	}

	public long getOriginalResourcePK() {
		return _originalResourcePK;
	}

	@JSON
	@Override
	public long getCauHoiId() {
		return _cauHoiId;
	}

	@Override
	public void setCauHoiId(long cauHoiId) {
		_cauHoiId = cauHoiId;
	}

	@JSON
	@Override
	public long getTraLoiId() {
		return _traLoiId;
	}

	@Override
	public void setTraLoiId(long traLoiId) {
		_traLoiId = traLoiId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DanhGiaHaiLong.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DanhGiaHaiLong toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DanhGiaHaiLong)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DanhGiaHaiLongImpl danhGiaHaiLongImpl = new DanhGiaHaiLongImpl();

		danhGiaHaiLongImpl.setDanhGiaHaiLongId(getDanhGiaHaiLongId());
		danhGiaHaiLongImpl.setGroupId(getGroupId());
		danhGiaHaiLongImpl.setCompanyId(getCompanyId());
		danhGiaHaiLongImpl.setUserId(getUserId());
		danhGiaHaiLongImpl.setUserName(getUserName());
		danhGiaHaiLongImpl.setCreateDate(getCreateDate());
		danhGiaHaiLongImpl.setModifiedDate(getModifiedDate());
		danhGiaHaiLongImpl.setResourceCode(getResourceCode());
		danhGiaHaiLongImpl.setResourcePK(getResourcePK());
		danhGiaHaiLongImpl.setCauHoiId(getCauHoiId());
		danhGiaHaiLongImpl.setTraLoiId(getTraLoiId());

		danhGiaHaiLongImpl.resetOriginalValues();

		return danhGiaHaiLongImpl;
	}

	@Override
	public int compareTo(DanhGiaHaiLong danhGiaHaiLong) {
		int value = 0;

		if (getDanhGiaHaiLongId() < danhGiaHaiLong.getDanhGiaHaiLongId()) {
			value = -1;
		}
		else if (getDanhGiaHaiLongId() > danhGiaHaiLong.getDanhGiaHaiLongId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DanhGiaHaiLong)) {
			return false;
		}

		DanhGiaHaiLong danhGiaHaiLong = (DanhGiaHaiLong)obj;

		long primaryKey = danhGiaHaiLong.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DanhGiaHaiLongModelImpl danhGiaHaiLongModelImpl = this;

		danhGiaHaiLongModelImpl._originalCompanyId = danhGiaHaiLongModelImpl._companyId;

		danhGiaHaiLongModelImpl._setOriginalCompanyId = false;

		danhGiaHaiLongModelImpl._originalResourceCode = danhGiaHaiLongModelImpl._resourceCode;

		danhGiaHaiLongModelImpl._setOriginalResourceCode = false;

		danhGiaHaiLongModelImpl._originalResourcePK = danhGiaHaiLongModelImpl._resourcePK;

		danhGiaHaiLongModelImpl._setOriginalResourcePK = false;

		danhGiaHaiLongModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DanhGiaHaiLong> toCacheModel() {
		DanhGiaHaiLongCacheModel danhGiaHaiLongCacheModel = new DanhGiaHaiLongCacheModel();

		danhGiaHaiLongCacheModel.danhGiaHaiLongId = getDanhGiaHaiLongId();

		danhGiaHaiLongCacheModel.groupId = getGroupId();

		danhGiaHaiLongCacheModel.companyId = getCompanyId();

		danhGiaHaiLongCacheModel.userId = getUserId();

		danhGiaHaiLongCacheModel.userName = getUserName();

		String userName = danhGiaHaiLongCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			danhGiaHaiLongCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			danhGiaHaiLongCacheModel.createDate = createDate.getTime();
		}
		else {
			danhGiaHaiLongCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			danhGiaHaiLongCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			danhGiaHaiLongCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		danhGiaHaiLongCacheModel.resourceCode = getResourceCode();

		danhGiaHaiLongCacheModel.resourcePK = getResourcePK();

		danhGiaHaiLongCacheModel.cauHoiId = getCauHoiId();

		danhGiaHaiLongCacheModel.traLoiId = getTraLoiId();

		return danhGiaHaiLongCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{danhGiaHaiLongId=");
		sb.append(getDanhGiaHaiLongId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", resourceCode=");
		sb.append(getResourceCode());
		sb.append(", resourcePK=");
		sb.append(getResourcePK());
		sb.append(", cauHoiId=");
		sb.append(getCauHoiId());
		sb.append(", traLoiId=");
		sb.append(getTraLoiId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>danhGiaHaiLongId</column-name><column-value><![CDATA[");
		sb.append(getDanhGiaHaiLongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourceCode</column-name><column-value><![CDATA[");
		sb.append(getResourceCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourcePK</column-name><column-value><![CDATA[");
		sb.append(getResourcePK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cauHoiId</column-name><column-value><![CDATA[");
		sb.append(getCauHoiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>traLoiId</column-name><column-value><![CDATA[");
		sb.append(getTraLoiId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DanhGiaHaiLong.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DanhGiaHaiLong.class
		};
	private long _danhGiaHaiLongId;
	private long _groupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _resourceCode;
	private long _originalResourceCode;
	private boolean _setOriginalResourceCode;
	private long _resourcePK;
	private long _originalResourcePK;
	private boolean _setOriginalResourcePK;
	private long _cauHoiId;
	private long _traLoiId;
	private long _columnBitmask;
	private DanhGiaHaiLong _escapedModel;
}