/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_gia_hai_long.service.base;

import com.alpha.portlet.danh_gia_hai_long.model.DanhGiaHaiLong;
import com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongService;
import com.alpha.portlet.danh_gia_hai_long.service.persistence.CauHoiFinder;
import com.alpha.portlet.danh_gia_hai_long.service.persistence.CauHoiPersistence;
import com.alpha.portlet.danh_gia_hai_long.service.persistence.DanhGiaHaiLongPersistence;
import com.alpha.portlet.danh_gia_hai_long.service.persistence.TraLoiPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the danh gia hai long remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.alpha.portlet.danh_gia_hai_long.service.impl.DanhGiaHaiLongServiceImpl}.
 * </p>
 *
 * @author darkn
 * @see com.alpha.portlet.danh_gia_hai_long.service.impl.DanhGiaHaiLongServiceImpl
 * @see com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongServiceUtil
 * @generated
 */
public abstract class DanhGiaHaiLongServiceBaseImpl extends BaseServiceImpl
	implements DanhGiaHaiLongService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongServiceUtil} to access the danh gia hai long remote service.
	 */

	/**
	 * Returns the cau hoi local service.
	 *
	 * @return the cau hoi local service
	 */
	public com.alpha.portlet.danh_gia_hai_long.service.CauHoiLocalService getCauHoiLocalService() {
		return cauHoiLocalService;
	}

	/**
	 * Sets the cau hoi local service.
	 *
	 * @param cauHoiLocalService the cau hoi local service
	 */
	public void setCauHoiLocalService(
		com.alpha.portlet.danh_gia_hai_long.service.CauHoiLocalService cauHoiLocalService) {
		this.cauHoiLocalService = cauHoiLocalService;
	}

	/**
	 * Returns the cau hoi remote service.
	 *
	 * @return the cau hoi remote service
	 */
	public com.alpha.portlet.danh_gia_hai_long.service.CauHoiService getCauHoiService() {
		return cauHoiService;
	}

	/**
	 * Sets the cau hoi remote service.
	 *
	 * @param cauHoiService the cau hoi remote service
	 */
	public void setCauHoiService(
		com.alpha.portlet.danh_gia_hai_long.service.CauHoiService cauHoiService) {
		this.cauHoiService = cauHoiService;
	}

	/**
	 * Returns the cau hoi persistence.
	 *
	 * @return the cau hoi persistence
	 */
	public CauHoiPersistence getCauHoiPersistence() {
		return cauHoiPersistence;
	}

	/**
	 * Sets the cau hoi persistence.
	 *
	 * @param cauHoiPersistence the cau hoi persistence
	 */
	public void setCauHoiPersistence(CauHoiPersistence cauHoiPersistence) {
		this.cauHoiPersistence = cauHoiPersistence;
	}

	/**
	 * Returns the cau hoi finder.
	 *
	 * @return the cau hoi finder
	 */
	public CauHoiFinder getCauHoiFinder() {
		return cauHoiFinder;
	}

	/**
	 * Sets the cau hoi finder.
	 *
	 * @param cauHoiFinder the cau hoi finder
	 */
	public void setCauHoiFinder(CauHoiFinder cauHoiFinder) {
		this.cauHoiFinder = cauHoiFinder;
	}

	/**
	 * Returns the danh gia hai long local service.
	 *
	 * @return the danh gia hai long local service
	 */
	public com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongLocalService getDanhGiaHaiLongLocalService() {
		return danhGiaHaiLongLocalService;
	}

	/**
	 * Sets the danh gia hai long local service.
	 *
	 * @param danhGiaHaiLongLocalService the danh gia hai long local service
	 */
	public void setDanhGiaHaiLongLocalService(
		com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongLocalService danhGiaHaiLongLocalService) {
		this.danhGiaHaiLongLocalService = danhGiaHaiLongLocalService;
	}

	/**
	 * Returns the danh gia hai long remote service.
	 *
	 * @return the danh gia hai long remote service
	 */
	public com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongService getDanhGiaHaiLongService() {
		return danhGiaHaiLongService;
	}

	/**
	 * Sets the danh gia hai long remote service.
	 *
	 * @param danhGiaHaiLongService the danh gia hai long remote service
	 */
	public void setDanhGiaHaiLongService(
		com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongService danhGiaHaiLongService) {
		this.danhGiaHaiLongService = danhGiaHaiLongService;
	}

	/**
	 * Returns the danh gia hai long persistence.
	 *
	 * @return the danh gia hai long persistence
	 */
	public DanhGiaHaiLongPersistence getDanhGiaHaiLongPersistence() {
		return danhGiaHaiLongPersistence;
	}

	/**
	 * Sets the danh gia hai long persistence.
	 *
	 * @param danhGiaHaiLongPersistence the danh gia hai long persistence
	 */
	public void setDanhGiaHaiLongPersistence(
		DanhGiaHaiLongPersistence danhGiaHaiLongPersistence) {
		this.danhGiaHaiLongPersistence = danhGiaHaiLongPersistence;
	}

	/**
	 * Returns the tra loi local service.
	 *
	 * @return the tra loi local service
	 */
	public com.alpha.portlet.danh_gia_hai_long.service.TraLoiLocalService getTraLoiLocalService() {
		return traLoiLocalService;
	}

	/**
	 * Sets the tra loi local service.
	 *
	 * @param traLoiLocalService the tra loi local service
	 */
	public void setTraLoiLocalService(
		com.alpha.portlet.danh_gia_hai_long.service.TraLoiLocalService traLoiLocalService) {
		this.traLoiLocalService = traLoiLocalService;
	}

	/**
	 * Returns the tra loi remote service.
	 *
	 * @return the tra loi remote service
	 */
	public com.alpha.portlet.danh_gia_hai_long.service.TraLoiService getTraLoiService() {
		return traLoiService;
	}

	/**
	 * Sets the tra loi remote service.
	 *
	 * @param traLoiService the tra loi remote service
	 */
	public void setTraLoiService(
		com.alpha.portlet.danh_gia_hai_long.service.TraLoiService traLoiService) {
		this.traLoiService = traLoiService;
	}

	/**
	 * Returns the tra loi persistence.
	 *
	 * @return the tra loi persistence
	 */
	public TraLoiPersistence getTraLoiPersistence() {
		return traLoiPersistence;
	}

	/**
	 * Sets the tra loi persistence.
	 *
	 * @param traLoiPersistence the tra loi persistence
	 */
	public void setTraLoiPersistence(TraLoiPersistence traLoiPersistence) {
		this.traLoiPersistence = traLoiPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return DanhGiaHaiLong.class;
	}

	protected String getModelClassName() {
		return DanhGiaHaiLong.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = danhGiaHaiLongPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.alpha.portlet.danh_gia_hai_long.service.CauHoiLocalService.class)
	protected com.alpha.portlet.danh_gia_hai_long.service.CauHoiLocalService cauHoiLocalService;
	@BeanReference(type = com.alpha.portlet.danh_gia_hai_long.service.CauHoiService.class)
	protected com.alpha.portlet.danh_gia_hai_long.service.CauHoiService cauHoiService;
	@BeanReference(type = CauHoiPersistence.class)
	protected CauHoiPersistence cauHoiPersistence;
	@BeanReference(type = CauHoiFinder.class)
	protected CauHoiFinder cauHoiFinder;
	@BeanReference(type = com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongLocalService.class)
	protected com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongLocalService danhGiaHaiLongLocalService;
	@BeanReference(type = com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongService.class)
	protected com.alpha.portlet.danh_gia_hai_long.service.DanhGiaHaiLongService danhGiaHaiLongService;
	@BeanReference(type = DanhGiaHaiLongPersistence.class)
	protected DanhGiaHaiLongPersistence danhGiaHaiLongPersistence;
	@BeanReference(type = com.alpha.portlet.danh_gia_hai_long.service.TraLoiLocalService.class)
	protected com.alpha.portlet.danh_gia_hai_long.service.TraLoiLocalService traLoiLocalService;
	@BeanReference(type = com.alpha.portlet.danh_gia_hai_long.service.TraLoiService.class)
	protected com.alpha.portlet.danh_gia_hai_long.service.TraLoiService traLoiService;
	@BeanReference(type = TraLoiPersistence.class)
	protected TraLoiPersistence traLoiPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private DanhGiaHaiLongServiceClpInvoker _clpInvoker = new DanhGiaHaiLongServiceClpInvoker();
}