/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.dmdc.model.impl;

import com.alpha.portlet.dmdc.model.BieuMauBaoCao;
import com.alpha.portlet.dmdc.model.BieuMauBaoCaoModel;
import com.alpha.portlet.dmdc.model.BieuMauBaoCaoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BieuMauBaoCao service. Represents a row in the &quot;alpha_dm_bieumaubaocao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.alpha.portlet.dmdc.model.BieuMauBaoCaoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BieuMauBaoCaoImpl}.
 * </p>
 *
 * @author darkn
 * @see BieuMauBaoCaoImpl
 * @see com.alpha.portlet.dmdc.model.BieuMauBaoCao
 * @see com.alpha.portlet.dmdc.model.BieuMauBaoCaoModel
 * @generated
 */
@JSON(strict = true)
public class BieuMauBaoCaoModelImpl extends BaseModelImpl<BieuMauBaoCao>
	implements BieuMauBaoCaoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bieu mau bao cao model instance should use the {@link com.alpha.portlet.dmdc.model.BieuMauBaoCao} interface instead.
	 */
	public static final String TABLE_NAME = "alpha_dm_bieumaubaocao";
	public static final Object[][] TABLE_COLUMNS = {
			{ "bieuMauBaoCaoId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "chuyenMucBieuMauId", Types.BIGINT },
			{ "ten", Types.VARCHAR },
			{ "ma", Types.VARCHAR },
			{ "moTa", Types.VARCHAR },
			{ "loai", Types.INTEGER },
			{ "hoatDong", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table alpha_dm_bieumaubaocao (bieuMauBaoCaoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,chuyenMucBieuMauId LONG,ten VARCHAR(75) null,ma VARCHAR(75) null,moTa VARCHAR(75) null,loai INTEGER,hoatDong BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table alpha_dm_bieumaubaocao";
	public static final String ORDER_BY_JPQL = " ORDER BY bieuMauBaoCao.bieuMauBaoCaoId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY alpha_dm_bieumaubaocao.bieuMauBaoCaoId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.alpha.portlet.dmdc.model.BieuMauBaoCao"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.alpha.portlet.dmdc.model.BieuMauBaoCao"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.alpha.portlet.dmdc.model.BieuMauBaoCao"),
			true);
	public static long CHUYENMUCBIEUMAUID_COLUMN_BITMASK = 1L;
	public static long COMPANYID_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long HOATDONG_COLUMN_BITMASK = 8L;
	public static long LOAI_COLUMN_BITMASK = 16L;
	public static long MA_COLUMN_BITMASK = 32L;
	public static long BIEUMAUBAOCAOID_COLUMN_BITMASK = 64L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BieuMauBaoCao toModel(BieuMauBaoCaoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BieuMauBaoCao model = new BieuMauBaoCaoImpl();

		model.setBieuMauBaoCaoId(soapModel.getBieuMauBaoCaoId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setChuyenMucBieuMauId(soapModel.getChuyenMucBieuMauId());
		model.setTen(soapModel.getTen());
		model.setMa(soapModel.getMa());
		model.setMoTa(soapModel.getMoTa());
		model.setLoai(soapModel.getLoai());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BieuMauBaoCao> toModels(BieuMauBaoCaoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BieuMauBaoCao> models = new ArrayList<BieuMauBaoCao>(soapModels.length);

		for (BieuMauBaoCaoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.alpha.portlet.dmdc.model.BieuMauBaoCao"));

	public BieuMauBaoCaoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bieuMauBaoCaoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBieuMauBaoCaoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bieuMauBaoCaoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BieuMauBaoCao.class;
	}

	@Override
	public String getModelClassName() {
		return BieuMauBaoCao.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("bieuMauBaoCaoId", getBieuMauBaoCaoId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("chuyenMucBieuMauId", getChuyenMucBieuMauId());
		attributes.put("ten", getTen());
		attributes.put("ma", getMa());
		attributes.put("moTa", getMoTa());
		attributes.put("loai", getLoai());
		attributes.put("hoatDong", getHoatDong());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long bieuMauBaoCaoId = (Long)attributes.get("bieuMauBaoCaoId");

		if (bieuMauBaoCaoId != null) {
			setBieuMauBaoCaoId(bieuMauBaoCaoId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long chuyenMucBieuMauId = (Long)attributes.get("chuyenMucBieuMauId");

		if (chuyenMucBieuMauId != null) {
			setChuyenMucBieuMauId(chuyenMucBieuMauId);
		}

		String ten = (String)attributes.get("ten");

		if (ten != null) {
			setTen(ten);
		}

		String ma = (String)attributes.get("ma");

		if (ma != null) {
			setMa(ma);
		}

		String moTa = (String)attributes.get("moTa");

		if (moTa != null) {
			setMoTa(moTa);
		}

		Integer loai = (Integer)attributes.get("loai");

		if (loai != null) {
			setLoai(loai);
		}

		Boolean hoatDong = (Boolean)attributes.get("hoatDong");

		if (hoatDong != null) {
			setHoatDong(hoatDong);
		}
	}

	@JSON
	@Override
	public long getBieuMauBaoCaoId() {
		return _bieuMauBaoCaoId;
	}

	@Override
	public void setBieuMauBaoCaoId(long bieuMauBaoCaoId) {
		_bieuMauBaoCaoId = bieuMauBaoCaoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getChuyenMucBieuMauId() {
		return _chuyenMucBieuMauId;
	}

	@Override
	public void setChuyenMucBieuMauId(long chuyenMucBieuMauId) {
		_columnBitmask |= CHUYENMUCBIEUMAUID_COLUMN_BITMASK;

		if (!_setOriginalChuyenMucBieuMauId) {
			_setOriginalChuyenMucBieuMauId = true;

			_originalChuyenMucBieuMauId = _chuyenMucBieuMauId;
		}

		_chuyenMucBieuMauId = chuyenMucBieuMauId;
	}

	public long getOriginalChuyenMucBieuMauId() {
		return _originalChuyenMucBieuMauId;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_ten = ten;
	}

	@JSON
	@Override
	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	@Override
	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	@JSON
	@Override
	public String getMoTa() {
		if (_moTa == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTa;
		}
	}

	@Override
	public void setMoTa(String moTa) {
		_moTa = moTa;
	}

	@JSON
	@Override
	public int getLoai() {
		return _loai;
	}

	@Override
	public void setLoai(int loai) {
		_columnBitmask |= LOAI_COLUMN_BITMASK;

		if (!_setOriginalLoai) {
			_setOriginalLoai = true;

			_originalLoai = _loai;
		}

		_loai = loai;
	}

	public int getOriginalLoai() {
		return _originalLoai;
	}

	@JSON
	@Override
	public boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public boolean isHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			BieuMauBaoCao.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BieuMauBaoCao toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BieuMauBaoCao)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BieuMauBaoCaoImpl bieuMauBaoCaoImpl = new BieuMauBaoCaoImpl();

		bieuMauBaoCaoImpl.setBieuMauBaoCaoId(getBieuMauBaoCaoId());
		bieuMauBaoCaoImpl.setGroupId(getGroupId());
		bieuMauBaoCaoImpl.setCompanyId(getCompanyId());
		bieuMauBaoCaoImpl.setUserId(getUserId());
		bieuMauBaoCaoImpl.setUserName(getUserName());
		bieuMauBaoCaoImpl.setCreateDate(getCreateDate());
		bieuMauBaoCaoImpl.setModifiedDate(getModifiedDate());
		bieuMauBaoCaoImpl.setChuyenMucBieuMauId(getChuyenMucBieuMauId());
		bieuMauBaoCaoImpl.setTen(getTen());
		bieuMauBaoCaoImpl.setMa(getMa());
		bieuMauBaoCaoImpl.setMoTa(getMoTa());
		bieuMauBaoCaoImpl.setLoai(getLoai());
		bieuMauBaoCaoImpl.setHoatDong(getHoatDong());

		bieuMauBaoCaoImpl.resetOriginalValues();

		return bieuMauBaoCaoImpl;
	}

	@Override
	public int compareTo(BieuMauBaoCao bieuMauBaoCao) {
		long primaryKey = bieuMauBaoCao.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BieuMauBaoCao)) {
			return false;
		}

		BieuMauBaoCao bieuMauBaoCao = (BieuMauBaoCao)obj;

		long primaryKey = bieuMauBaoCao.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BieuMauBaoCaoModelImpl bieuMauBaoCaoModelImpl = this;

		bieuMauBaoCaoModelImpl._originalGroupId = bieuMauBaoCaoModelImpl._groupId;

		bieuMauBaoCaoModelImpl._setOriginalGroupId = false;

		bieuMauBaoCaoModelImpl._originalCompanyId = bieuMauBaoCaoModelImpl._companyId;

		bieuMauBaoCaoModelImpl._setOriginalCompanyId = false;

		bieuMauBaoCaoModelImpl._originalChuyenMucBieuMauId = bieuMauBaoCaoModelImpl._chuyenMucBieuMauId;

		bieuMauBaoCaoModelImpl._setOriginalChuyenMucBieuMauId = false;

		bieuMauBaoCaoModelImpl._originalMa = bieuMauBaoCaoModelImpl._ma;

		bieuMauBaoCaoModelImpl._originalLoai = bieuMauBaoCaoModelImpl._loai;

		bieuMauBaoCaoModelImpl._setOriginalLoai = false;

		bieuMauBaoCaoModelImpl._originalHoatDong = bieuMauBaoCaoModelImpl._hoatDong;

		bieuMauBaoCaoModelImpl._setOriginalHoatDong = false;

		bieuMauBaoCaoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BieuMauBaoCao> toCacheModel() {
		BieuMauBaoCaoCacheModel bieuMauBaoCaoCacheModel = new BieuMauBaoCaoCacheModel();

		bieuMauBaoCaoCacheModel.bieuMauBaoCaoId = getBieuMauBaoCaoId();

		bieuMauBaoCaoCacheModel.groupId = getGroupId();

		bieuMauBaoCaoCacheModel.companyId = getCompanyId();

		bieuMauBaoCaoCacheModel.userId = getUserId();

		bieuMauBaoCaoCacheModel.userName = getUserName();

		String userName = bieuMauBaoCaoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			bieuMauBaoCaoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			bieuMauBaoCaoCacheModel.createDate = createDate.getTime();
		}
		else {
			bieuMauBaoCaoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			bieuMauBaoCaoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			bieuMauBaoCaoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		bieuMauBaoCaoCacheModel.chuyenMucBieuMauId = getChuyenMucBieuMauId();

		bieuMauBaoCaoCacheModel.ten = getTen();

		String ten = bieuMauBaoCaoCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			bieuMauBaoCaoCacheModel.ten = null;
		}

		bieuMauBaoCaoCacheModel.ma = getMa();

		String ma = bieuMauBaoCaoCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			bieuMauBaoCaoCacheModel.ma = null;
		}

		bieuMauBaoCaoCacheModel.moTa = getMoTa();

		String moTa = bieuMauBaoCaoCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			bieuMauBaoCaoCacheModel.moTa = null;
		}

		bieuMauBaoCaoCacheModel.loai = getLoai();

		bieuMauBaoCaoCacheModel.hoatDong = getHoatDong();

		return bieuMauBaoCaoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{bieuMauBaoCaoId=");
		sb.append(getBieuMauBaoCaoId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", chuyenMucBieuMauId=");
		sb.append(getChuyenMucBieuMauId());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", moTa=");
		sb.append(getMoTa());
		sb.append(", loai=");
		sb.append(getLoai());
		sb.append(", hoatDong=");
		sb.append(getHoatDong());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.alpha.portlet.dmdc.model.BieuMauBaoCao");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>bieuMauBaoCaoId</column-name><column-value><![CDATA[");
		sb.append(getBieuMauBaoCaoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chuyenMucBieuMauId</column-name><column-value><![CDATA[");
		sb.append(getChuyenMucBieuMauId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTa</column-name><column-value><![CDATA[");
		sb.append(getMoTa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loai</column-name><column-value><![CDATA[");
		sb.append(getLoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoatDong</column-name><column-value><![CDATA[");
		sb.append(getHoatDong());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BieuMauBaoCao.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BieuMauBaoCao.class
		};
	private long _bieuMauBaoCaoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _chuyenMucBieuMauId;
	private long _originalChuyenMucBieuMauId;
	private boolean _setOriginalChuyenMucBieuMauId;
	private String _ten;
	private String _ma;
	private String _originalMa;
	private String _moTa;
	private int _loai;
	private int _originalLoai;
	private boolean _setOriginalLoai;
	private boolean _hoatDong;
	private boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private long _columnBitmask;
	private BieuMauBaoCao _escapedModel;
}