/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.dmdc.model.impl;

import com.alpha.portlet.dmdc.model.CauHinh;
import com.alpha.portlet.dmdc.model.CauHinhModel;
import com.alpha.portlet.dmdc.model.CauHinhSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CauHinh service. Represents a row in the &quot;alpha_dm_cauhinh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.alpha.portlet.dmdc.model.CauHinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CauHinhImpl}.
 * </p>
 *
 * @author darkn
 * @see CauHinhImpl
 * @see com.alpha.portlet.dmdc.model.CauHinh
 * @see com.alpha.portlet.dmdc.model.CauHinhModel
 * @generated
 */
@JSON(strict = true)
public class CauHinhModelImpl extends BaseModelImpl<CauHinh>
	implements CauHinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cau hinh model instance should use the {@link com.alpha.portlet.dmdc.model.CauHinh} interface instead.
	 */
	public static final String TABLE_NAME = "alpha_dm_cauhinh";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cauHinhId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "portletId", Types.VARCHAR },
			{ "resourceCodeId", Types.BIGINT },
			{ "primKey", Types.BIGINT },
			{ "preferences", Types.VARCHAR },
			{ "type_", Types.INTEGER },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table alpha_dm_cauhinh (cauHinhId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,portletId VARCHAR(75) null,resourceCodeId LONG,primKey LONG,preferences VARCHAR(75) null,type_ INTEGER,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table alpha_dm_cauhinh";
	public static final String ORDER_BY_JPQL = " ORDER BY cauHinh.cauHinhId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY alpha_dm_cauhinh.cauHinhId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.alpha.portlet.dmdc.model.CauHinh"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.alpha.portlet.dmdc.model.CauHinh"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.alpha.portlet.dmdc.model.CauHinh"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long PORTLETID_COLUMN_BITMASK = 4L;
	public static long PRIMKEY_COLUMN_BITMASK = 8L;
	public static long RESOURCECODEID_COLUMN_BITMASK = 16L;
	public static long TYPE_COLUMN_BITMASK = 32L;
	public static long CAUHINHID_COLUMN_BITMASK = 64L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CauHinh toModel(CauHinhSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CauHinh model = new CauHinhImpl();

		model.setCauHinhId(soapModel.getCauHinhId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPortletId(soapModel.getPortletId());
		model.setResourceCodeId(soapModel.getResourceCodeId());
		model.setPrimKey(soapModel.getPrimKey());
		model.setPreferences(soapModel.getPreferences());
		model.setType(soapModel.getType());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CauHinh> toModels(CauHinhSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CauHinh> models = new ArrayList<CauHinh>(soapModels.length);

		for (CauHinhSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.alpha.portlet.dmdc.model.CauHinh"));

	public CauHinhModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cauHinhId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCauHinhId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cauHinhId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CauHinh.class;
	}

	@Override
	public String getModelClassName() {
		return CauHinh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cauHinhId", getCauHinhId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("portletId", getPortletId());
		attributes.put("resourceCodeId", getResourceCodeId());
		attributes.put("primKey", getPrimKey());
		attributes.put("preferences", getPreferences());
		attributes.put("type", getType());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cauHinhId = (Long)attributes.get("cauHinhId");

		if (cauHinhId != null) {
			setCauHinhId(cauHinhId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String portletId = (String)attributes.get("portletId");

		if (portletId != null) {
			setPortletId(portletId);
		}

		Long resourceCodeId = (Long)attributes.get("resourceCodeId");

		if (resourceCodeId != null) {
			setResourceCodeId(resourceCodeId);
		}

		Long primKey = (Long)attributes.get("primKey");

		if (primKey != null) {
			setPrimKey(primKey);
		}

		String preferences = (String)attributes.get("preferences");

		if (preferences != null) {
			setPreferences(preferences);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@JSON
	@Override
	public long getCauHinhId() {
		return _cauHinhId;
	}

	@Override
	public void setCauHinhId(long cauHinhId) {
		_cauHinhId = cauHinhId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getPortletId() {
		if (_portletId == null) {
			return StringPool.BLANK;
		}
		else {
			return _portletId;
		}
	}

	@Override
	public void setPortletId(String portletId) {
		_columnBitmask |= PORTLETID_COLUMN_BITMASK;

		if (_originalPortletId == null) {
			_originalPortletId = _portletId;
		}

		_portletId = portletId;
	}

	public String getOriginalPortletId() {
		return GetterUtil.getString(_originalPortletId);
	}

	@JSON
	@Override
	public long getResourceCodeId() {
		return _resourceCodeId;
	}

	@Override
	public void setResourceCodeId(long resourceCodeId) {
		_columnBitmask |= RESOURCECODEID_COLUMN_BITMASK;

		if (!_setOriginalResourceCodeId) {
			_setOriginalResourceCodeId = true;

			_originalResourceCodeId = _resourceCodeId;
		}

		_resourceCodeId = resourceCodeId;
	}

	public long getOriginalResourceCodeId() {
		return _originalResourceCodeId;
	}

	@JSON
	@Override
	public long getPrimKey() {
		return _primKey;
	}

	@Override
	public void setPrimKey(long primKey) {
		_columnBitmask |= PRIMKEY_COLUMN_BITMASK;

		if (!_setOriginalPrimKey) {
			_setOriginalPrimKey = true;

			_originalPrimKey = _primKey;
		}

		_primKey = primKey;
	}

	public long getOriginalPrimKey() {
		return _originalPrimKey;
	}

	@JSON
	@Override
	public String getPreferences() {
		if (_preferences == null) {
			return StringPool.BLANK;
		}
		else {
			return _preferences;
		}
	}

	@Override
	public void setPreferences(String preferences) {
		_preferences = preferences;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CauHinh.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CauHinh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CauHinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CauHinhImpl cauHinhImpl = new CauHinhImpl();

		cauHinhImpl.setCauHinhId(getCauHinhId());
		cauHinhImpl.setGroupId(getGroupId());
		cauHinhImpl.setCompanyId(getCompanyId());
		cauHinhImpl.setUserId(getUserId());
		cauHinhImpl.setUserName(getUserName());
		cauHinhImpl.setCreateDate(getCreateDate());
		cauHinhImpl.setModifiedDate(getModifiedDate());
		cauHinhImpl.setPortletId(getPortletId());
		cauHinhImpl.setResourceCodeId(getResourceCodeId());
		cauHinhImpl.setPrimKey(getPrimKey());
		cauHinhImpl.setPreferences(getPreferences());
		cauHinhImpl.setType(getType());
		cauHinhImpl.setDescription(getDescription());

		cauHinhImpl.resetOriginalValues();

		return cauHinhImpl;
	}

	@Override
	public int compareTo(CauHinh cauHinh) {
		long primaryKey = cauHinh.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CauHinh)) {
			return false;
		}

		CauHinh cauHinh = (CauHinh)obj;

		long primaryKey = cauHinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CauHinhModelImpl cauHinhModelImpl = this;

		cauHinhModelImpl._originalGroupId = cauHinhModelImpl._groupId;

		cauHinhModelImpl._setOriginalGroupId = false;

		cauHinhModelImpl._originalCompanyId = cauHinhModelImpl._companyId;

		cauHinhModelImpl._setOriginalCompanyId = false;

		cauHinhModelImpl._originalPortletId = cauHinhModelImpl._portletId;

		cauHinhModelImpl._originalResourceCodeId = cauHinhModelImpl._resourceCodeId;

		cauHinhModelImpl._setOriginalResourceCodeId = false;

		cauHinhModelImpl._originalPrimKey = cauHinhModelImpl._primKey;

		cauHinhModelImpl._setOriginalPrimKey = false;

		cauHinhModelImpl._originalType = cauHinhModelImpl._type;

		cauHinhModelImpl._setOriginalType = false;

		cauHinhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CauHinh> toCacheModel() {
		CauHinhCacheModel cauHinhCacheModel = new CauHinhCacheModel();

		cauHinhCacheModel.cauHinhId = getCauHinhId();

		cauHinhCacheModel.groupId = getGroupId();

		cauHinhCacheModel.companyId = getCompanyId();

		cauHinhCacheModel.userId = getUserId();

		cauHinhCacheModel.userName = getUserName();

		String userName = cauHinhCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cauHinhCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cauHinhCacheModel.createDate = createDate.getTime();
		}
		else {
			cauHinhCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cauHinhCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cauHinhCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cauHinhCacheModel.portletId = getPortletId();

		String portletId = cauHinhCacheModel.portletId;

		if ((portletId != null) && (portletId.length() == 0)) {
			cauHinhCacheModel.portletId = null;
		}

		cauHinhCacheModel.resourceCodeId = getResourceCodeId();

		cauHinhCacheModel.primKey = getPrimKey();

		cauHinhCacheModel.preferences = getPreferences();

		String preferences = cauHinhCacheModel.preferences;

		if ((preferences != null) && (preferences.length() == 0)) {
			cauHinhCacheModel.preferences = null;
		}

		cauHinhCacheModel.type = getType();

		cauHinhCacheModel.description = getDescription();

		String description = cauHinhCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			cauHinhCacheModel.description = null;
		}

		return cauHinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{cauHinhId=");
		sb.append(getCauHinhId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", portletId=");
		sb.append(getPortletId());
		sb.append(", resourceCodeId=");
		sb.append(getResourceCodeId());
		sb.append(", primKey=");
		sb.append(getPrimKey());
		sb.append(", preferences=");
		sb.append(getPreferences());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.alpha.portlet.dmdc.model.CauHinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cauHinhId</column-name><column-value><![CDATA[");
		sb.append(getCauHinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portletId</column-name><column-value><![CDATA[");
		sb.append(getPortletId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourceCodeId</column-name><column-value><![CDATA[");
		sb.append(getResourceCodeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primKey</column-name><column-value><![CDATA[");
		sb.append(getPrimKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>preferences</column-name><column-value><![CDATA[");
		sb.append(getPreferences());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CauHinh.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CauHinh.class
		};
	private long _cauHinhId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _portletId;
	private String _originalPortletId;
	private long _resourceCodeId;
	private long _originalResourceCodeId;
	private boolean _setOriginalResourceCodeId;
	private long _primKey;
	private long _originalPrimKey;
	private boolean _setOriginalPrimKey;
	private String _preferences;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private String _description;
	private long _columnBitmask;
	private CauHinh _escapedModel;
}