/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.dmdc.model.impl;

import com.alpha.portlet.dmdc.model.FileDinhKem;
import com.alpha.portlet.dmdc.model.FileDinhKemModel;
import com.alpha.portlet.dmdc.model.FileDinhKemSoap;
import com.alpha.portlet.dmdc.service.persistence.FileDinhKemPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FileDinhKem service. Represents a row in the &quot;alpha_dm_filedinhkem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.alpha.portlet.dmdc.model.FileDinhKemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FileDinhKemImpl}.
 * </p>
 *
 * @author darkn
 * @see FileDinhKemImpl
 * @see com.alpha.portlet.dmdc.model.FileDinhKem
 * @see com.alpha.portlet.dmdc.model.FileDinhKemModel
 * @generated
 */
@JSON(strict = true)
public class FileDinhKemModelImpl extends BaseModelImpl<FileDinhKem>
	implements FileDinhKemModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a file dinh kem model instance should use the {@link com.alpha.portlet.dmdc.model.FileDinhKem} interface instead.
	 */
	public static final String TABLE_NAME = "alpha_dm_filedinhkem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "resourceCode", Types.BIGINT },
			{ "primKey", Types.BIGINT },
			{ "fileEntryId", Types.BIGINT },
			{ "nhanQuaMang", Types.BOOLEAN },
			{ "extension", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table alpha_dm_filedinhkem (resourceCode LONG not null,primKey LONG not null,fileEntryId LONG not null,nhanQuaMang BOOLEAN,extension VARCHAR(75) null,primary key (resourceCode, primKey, fileEntryId))";
	public static final String TABLE_SQL_DROP = "drop table alpha_dm_filedinhkem";
	public static final String ORDER_BY_JPQL = " ORDER BY fileDinhKem.id.resourceCode ASC, fileDinhKem.id.primKey ASC, fileDinhKem.id.fileEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY alpha_dm_filedinhkem.resourceCode ASC, alpha_dm_filedinhkem.primKey ASC, alpha_dm_filedinhkem.fileEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.alpha.portlet.dmdc.model.FileDinhKem"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.alpha.portlet.dmdc.model.FileDinhKem"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.alpha.portlet.dmdc.model.FileDinhKem"),
			true);
	public static long FILEENTRYID_COLUMN_BITMASK = 1L;
	public static long PRIMKEY_COLUMN_BITMASK = 2L;
	public static long RESOURCECODE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FileDinhKem toModel(FileDinhKemSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FileDinhKem model = new FileDinhKemImpl();

		model.setResourceCode(soapModel.getResourceCode());
		model.setPrimKey(soapModel.getPrimKey());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setNhanQuaMang(soapModel.getNhanQuaMang());
		model.setExtension(soapModel.getExtension());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FileDinhKem> toModels(FileDinhKemSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FileDinhKem> models = new ArrayList<FileDinhKem>(soapModels.length);

		for (FileDinhKemSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.alpha.portlet.dmdc.model.FileDinhKem"));

	public FileDinhKemModelImpl() {
	}

	@Override
	public FileDinhKemPK getPrimaryKey() {
		return new FileDinhKemPK(_resourceCode, _primKey, _fileEntryId);
	}

	@Override
	public void setPrimaryKey(FileDinhKemPK primaryKey) {
		setResourceCode(primaryKey.resourceCode);
		setPrimKey(primaryKey.primKey);
		setFileEntryId(primaryKey.fileEntryId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new FileDinhKemPK(_resourceCode, _primKey, _fileEntryId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((FileDinhKemPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return FileDinhKem.class;
	}

	@Override
	public String getModelClassName() {
		return FileDinhKem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("resourceCode", getResourceCode());
		attributes.put("primKey", getPrimKey());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("nhanQuaMang", getNhanQuaMang());
		attributes.put("extension", getExtension());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long resourceCode = (Long)attributes.get("resourceCode");

		if (resourceCode != null) {
			setResourceCode(resourceCode);
		}

		Long primKey = (Long)attributes.get("primKey");

		if (primKey != null) {
			setPrimKey(primKey);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		Boolean nhanQuaMang = (Boolean)attributes.get("nhanQuaMang");

		if (nhanQuaMang != null) {
			setNhanQuaMang(nhanQuaMang);
		}

		String extension = (String)attributes.get("extension");

		if (extension != null) {
			setExtension(extension);
		}
	}

	@JSON
	@Override
	public long getResourceCode() {
		return _resourceCode;
	}

	@Override
	public void setResourceCode(long resourceCode) {
		_columnBitmask |= RESOURCECODE_COLUMN_BITMASK;

		if (!_setOriginalResourceCode) {
			_setOriginalResourceCode = true;

			_originalResourceCode = _resourceCode;
		}

		_resourceCode = resourceCode;
	}

	public long getOriginalResourceCode() {
		return _originalResourceCode;
	}

	@JSON
	@Override
	public long getPrimKey() {
		return _primKey;
	}

	@Override
	public void setPrimKey(long primKey) {
		_columnBitmask |= PRIMKEY_COLUMN_BITMASK;

		if (!_setOriginalPrimKey) {
			_setOriginalPrimKey = true;

			_originalPrimKey = _primKey;
		}

		_primKey = primKey;
	}

	public long getOriginalPrimKey() {
		return _originalPrimKey;
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_columnBitmask |= FILEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalFileEntryId) {
			_setOriginalFileEntryId = true;

			_originalFileEntryId = _fileEntryId;
		}

		_fileEntryId = fileEntryId;
	}

	public long getOriginalFileEntryId() {
		return _originalFileEntryId;
	}

	@JSON
	@Override
	public boolean getNhanQuaMang() {
		return _nhanQuaMang;
	}

	@Override
	public boolean isNhanQuaMang() {
		return _nhanQuaMang;
	}

	@Override
	public void setNhanQuaMang(boolean nhanQuaMang) {
		_nhanQuaMang = nhanQuaMang;
	}

	@JSON
	@Override
	public String getExtension() {
		if (_extension == null) {
			return StringPool.BLANK;
		}
		else {
			return _extension;
		}
	}

	@Override
	public void setExtension(String extension) {
		_extension = extension;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public FileDinhKem toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FileDinhKem)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FileDinhKemImpl fileDinhKemImpl = new FileDinhKemImpl();

		fileDinhKemImpl.setResourceCode(getResourceCode());
		fileDinhKemImpl.setPrimKey(getPrimKey());
		fileDinhKemImpl.setFileEntryId(getFileEntryId());
		fileDinhKemImpl.setNhanQuaMang(getNhanQuaMang());
		fileDinhKemImpl.setExtension(getExtension());

		fileDinhKemImpl.resetOriginalValues();

		return fileDinhKemImpl;
	}

	@Override
	public int compareTo(FileDinhKem fileDinhKem) {
		FileDinhKemPK primaryKey = fileDinhKem.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FileDinhKem)) {
			return false;
		}

		FileDinhKem fileDinhKem = (FileDinhKem)obj;

		FileDinhKemPK primaryKey = fileDinhKem.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		FileDinhKemModelImpl fileDinhKemModelImpl = this;

		fileDinhKemModelImpl._originalResourceCode = fileDinhKemModelImpl._resourceCode;

		fileDinhKemModelImpl._setOriginalResourceCode = false;

		fileDinhKemModelImpl._originalPrimKey = fileDinhKemModelImpl._primKey;

		fileDinhKemModelImpl._setOriginalPrimKey = false;

		fileDinhKemModelImpl._originalFileEntryId = fileDinhKemModelImpl._fileEntryId;

		fileDinhKemModelImpl._setOriginalFileEntryId = false;

		fileDinhKemModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FileDinhKem> toCacheModel() {
		FileDinhKemCacheModel fileDinhKemCacheModel = new FileDinhKemCacheModel();

		fileDinhKemCacheModel.resourceCode = getResourceCode();

		fileDinhKemCacheModel.primKey = getPrimKey();

		fileDinhKemCacheModel.fileEntryId = getFileEntryId();

		fileDinhKemCacheModel.nhanQuaMang = getNhanQuaMang();

		fileDinhKemCacheModel.extension = getExtension();

		String extension = fileDinhKemCacheModel.extension;

		if ((extension != null) && (extension.length() == 0)) {
			fileDinhKemCacheModel.extension = null;
		}

		return fileDinhKemCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{resourceCode=");
		sb.append(getResourceCode());
		sb.append(", primKey=");
		sb.append(getPrimKey());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", nhanQuaMang=");
		sb.append(getNhanQuaMang());
		sb.append(", extension=");
		sb.append(getExtension());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.alpha.portlet.dmdc.model.FileDinhKem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>resourceCode</column-name><column-value><![CDATA[");
		sb.append(getResourceCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primKey</column-name><column-value><![CDATA[");
		sb.append(getPrimKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhanQuaMang</column-name><column-value><![CDATA[");
		sb.append(getNhanQuaMang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extension</column-name><column-value><![CDATA[");
		sb.append(getExtension());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FileDinhKem.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FileDinhKem.class
		};
	private long _resourceCode;
	private long _originalResourceCode;
	private boolean _setOriginalResourceCode;
	private long _primKey;
	private long _originalPrimKey;
	private boolean _setOriginalPrimKey;
	private long _fileEntryId;
	private long _originalFileEntryId;
	private boolean _setOriginalFileEntryId;
	private boolean _nhanQuaMang;
	private String _extension;
	private long _columnBitmask;
	private FileDinhKem _escapedModel;
}