/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.quy_hoach.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BieuDoQuyHoach service. Represents a row in the &quot;alpha_bdqh_bieudoquyhoach&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alpha.portlet.quy_hoach.model.impl.BieuDoQuyHoachModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alpha.portlet.quy_hoach.model.impl.BieuDoQuyHoachImpl}.
 * </p>
 *
 * @author annn
 * @see BieuDoQuyHoach
 * @see com.alpha.portlet.quy_hoach.model.impl.BieuDoQuyHoachImpl
 * @see com.alpha.portlet.quy_hoach.model.impl.BieuDoQuyHoachModelImpl
 * @generated
 */
public interface BieuDoQuyHoachModel extends BaseModel<BieuDoQuyHoach>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bieu do quy hoach model instance should use the {@link BieuDoQuyHoach} interface instead.
	 */

	/**
	 * Returns the primary key of this bieu do quy hoach.
	 *
	 * @return the primary key of this bieu do quy hoach
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bieu do quy hoach.
	 *
	 * @param primaryKey the primary key of this bieu do quy hoach
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bieu do quy hoach ID of this bieu do quy hoach.
	 *
	 * @return the bieu do quy hoach ID of this bieu do quy hoach
	 */
	public long getBieuDoQuyHoachId();

	/**
	 * Sets the bieu do quy hoach ID of this bieu do quy hoach.
	 *
	 * @param bieuDoQuyHoachId the bieu do quy hoach ID of this bieu do quy hoach
	 */
	public void setBieuDoQuyHoachId(long bieuDoQuyHoachId);

	/**
	 * Returns the group ID of this bieu do quy hoach.
	 *
	 * @return the group ID of this bieu do quy hoach
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this bieu do quy hoach.
	 *
	 * @param groupId the group ID of this bieu do quy hoach
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this bieu do quy hoach.
	 *
	 * @return the company ID of this bieu do quy hoach
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bieu do quy hoach.
	 *
	 * @param companyId the company ID of this bieu do quy hoach
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bieu do quy hoach.
	 *
	 * @return the user ID of this bieu do quy hoach
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bieu do quy hoach.
	 *
	 * @param userId the user ID of this bieu do quy hoach
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bieu do quy hoach.
	 *
	 * @return the user uuid of this bieu do quy hoach
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this bieu do quy hoach.
	 *
	 * @param userUuid the user uuid of this bieu do quy hoach
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bieu do quy hoach.
	 *
	 * @return the user name of this bieu do quy hoach
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bieu do quy hoach.
	 *
	 * @param userName the user name of this bieu do quy hoach
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bieu do quy hoach.
	 *
	 * @return the create date of this bieu do quy hoach
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bieu do quy hoach.
	 *
	 * @param createDate the create date of this bieu do quy hoach
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bieu do quy hoach.
	 *
	 * @return the modified date of this bieu do quy hoach
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bieu do quy hoach.
	 *
	 * @param modifiedDate the modified date of this bieu do quy hoach
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this bieu do quy hoach.
	 *
	 * @return the ten of this bieu do quy hoach
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this bieu do quy hoach.
	 *
	 * @param ten the ten of this bieu do quy hoach
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma of this bieu do quy hoach.
	 *
	 * @return the ma of this bieu do quy hoach
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this bieu do quy hoach.
	 *
	 * @param ma the ma of this bieu do quy hoach
	 */
	public void setMa(String ma);

	/**
	 * Returns the mo ta of this bieu do quy hoach.
	 *
	 * @return the mo ta of this bieu do quy hoach
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this bieu do quy hoach.
	 *
	 * @param moTa the mo ta of this bieu do quy hoach
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the url file of this bieu do quy hoach.
	 *
	 * @return the url file of this bieu do quy hoach
	 */
	@AutoEscape
	public String getUrlFile();

	/**
	 * Sets the url file of this bieu do quy hoach.
	 *
	 * @param urlFile the url file of this bieu do quy hoach
	 */
	public void setUrlFile(String urlFile);

	/**
	 * Returns the hoat dong of this bieu do quy hoach.
	 *
	 * @return the hoat dong of this bieu do quy hoach
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this bieu do quy hoach is hoat dong.
	 *
	 * @return <code>true</code> if this bieu do quy hoach is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this bieu do quy hoach is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this bieu do quy hoach
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the do uu tien of this bieu do quy hoach.
	 *
	 * @return the do uu tien of this bieu do quy hoach
	 */
	public int getDoUuTien();

	/**
	 * Sets the do uu tien of this bieu do quy hoach.
	 *
	 * @param doUuTien the do uu tien of this bieu do quy hoach
	 */
	public void setDoUuTien(int doUuTien);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.alpha.portlet.quy_hoach.model.BieuDoQuyHoach bieuDoQuyHoach);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alpha.portlet.quy_hoach.model.BieuDoQuyHoach> toCacheModel();

	@Override
	public com.alpha.portlet.quy_hoach.model.BieuDoQuyHoach toEscapedModel();

	@Override
	public com.alpha.portlet.quy_hoach.model.BieuDoQuyHoach toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}