/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_muc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LoaiHoSo service. Represents a row in the &quot;alpha_dm_loaihoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alpha.portlet.danh_muc.model.impl.LoaiHoSoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alpha.portlet.danh_muc.model.impl.LoaiHoSoImpl}.
 * </p>
 *
 * @author darkn
 * @see LoaiHoSo
 * @see com.alpha.portlet.danh_muc.model.impl.LoaiHoSoImpl
 * @see com.alpha.portlet.danh_muc.model.impl.LoaiHoSoModelImpl
 * @generated
 */
public interface LoaiHoSoModel extends BaseModel<LoaiHoSo>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loai ho so model instance should use the {@link LoaiHoSo} interface instead.
	 */

	/**
	 * Returns the primary key of this loai ho so.
	 *
	 * @return the primary key of this loai ho so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loai ho so.
	 *
	 * @param primaryKey the primary key of this loai ho so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loai ho so ID of this loai ho so.
	 *
	 * @return the loai ho so ID of this loai ho so
	 */
	public long getLoaiHoSoId();

	/**
	 * Sets the loai ho so ID of this loai ho so.
	 *
	 * @param loaiHoSoId the loai ho so ID of this loai ho so
	 */
	public void setLoaiHoSoId(long loaiHoSoId);

	/**
	 * Returns the group ID of this loai ho so.
	 *
	 * @return the group ID of this loai ho so
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this loai ho so.
	 *
	 * @param groupId the group ID of this loai ho so
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this loai ho so.
	 *
	 * @return the company ID of this loai ho so
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loai ho so.
	 *
	 * @param companyId the company ID of this loai ho so
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loai ho so.
	 *
	 * @return the user ID of this loai ho so
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loai ho so.
	 *
	 * @param userId the user ID of this loai ho so
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loai ho so.
	 *
	 * @return the user uuid of this loai ho so
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this loai ho so.
	 *
	 * @param userUuid the user uuid of this loai ho so
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loai ho so.
	 *
	 * @return the user name of this loai ho so
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loai ho so.
	 *
	 * @param userName the user name of this loai ho so
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loai ho so.
	 *
	 * @return the create date of this loai ho so
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loai ho so.
	 *
	 * @param createDate the create date of this loai ho so
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loai ho so.
	 *
	 * @return the modified date of this loai ho so
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loai ho so.
	 *
	 * @param modifiedDate the modified date of this loai ho so
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the linh vuc ID of this loai ho so.
	 *
	 * @return the linh vuc ID of this loai ho so
	 */
	public long getLinhVucId();

	/**
	 * Sets the linh vuc ID of this loai ho so.
	 *
	 * @param linhVucId the linh vuc ID of this loai ho so
	 */
	public void setLinhVucId(long linhVucId);

	/**
	 * Returns the ten of this loai ho so.
	 *
	 * @return the ten of this loai ho so
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this loai ho so.
	 *
	 * @param ten the ten of this loai ho so
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma of this loai ho so.
	 *
	 * @return the ma of this loai ho so
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this loai ho so.
	 *
	 * @param ma the ma of this loai ho so
	 */
	public void setMa(String ma);

	/**
	 * Returns the mo ta of this loai ho so.
	 *
	 * @return the mo ta of this loai ho so
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this loai ho so.
	 *
	 * @param moTa the mo ta of this loai ho so
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the hoat dong of this loai ho so.
	 *
	 * @return the hoat dong of this loai ho so
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this loai ho so is hoat dong.
	 *
	 * @return <code>true</code> if this loai ho so is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this loai ho so is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this loai ho so
	 */
	public void setHoatDong(boolean hoatDong);

	/**
	 * Returns the do uu tien of this loai ho so.
	 *
	 * @return the do uu tien of this loai ho so
	 */
	public int getDoUuTien();

	/**
	 * Sets the do uu tien of this loai ho so.
	 *
	 * @param doUuTien the do uu tien of this loai ho so
	 */
	public void setDoUuTien(int doUuTien);

	/**
	 * Returns the bai viet u r l of this loai ho so.
	 *
	 * @return the bai viet u r l of this loai ho so
	 */
	@AutoEscape
	public String getBaiVietURL();

	/**
	 * Sets the bai viet u r l of this loai ho so.
	 *
	 * @param baiVietURL the bai viet u r l of this loai ho so
	 */
	public void setBaiVietURL(String baiVietURL);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.alpha.portlet.danh_muc.model.LoaiHoSo loaiHoSo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alpha.portlet.danh_muc.model.LoaiHoSo> toCacheModel();

	@Override
	public com.alpha.portlet.danh_muc.model.LoaiHoSo toEscapedModel();

	@Override
	public com.alpha.portlet.danh_muc.model.LoaiHoSo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}