/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_muc.model.impl;

import com.alpha.portlet.danh_muc.model.LinhVuc;
import com.alpha.portlet.danh_muc.service.LinhVucLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LinhVuc service. Represents a row in the &quot;alpha_dm_linhvuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LinhVucImpl}.
 * </p>
 *
 * @author darkn
 * @see LinhVucImpl
 * @see com.alpha.portlet.danh_muc.model.LinhVuc
 * @generated
 */
public abstract class LinhVucBaseImpl extends LinhVucModelImpl
	implements LinhVuc {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a linh vuc model instance should use the {@link LinhVuc} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			LinhVucLocalServiceUtil.addLinhVuc(this);
		}
		else {
			LinhVucLocalServiceUtil.updateLinhVuc(this);
		}
	}
}