/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.danh_muc.model.impl;

import com.alpha.portlet.danh_muc.model.LoaiHoSo;
import com.alpha.portlet.danh_muc.service.LoaiHoSoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LoaiHoSo service. Represents a row in the &quot;alpha_dm_loaihoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoaiHoSoImpl}.
 * </p>
 *
 * @author darkn
 * @see LoaiHoSoImpl
 * @see com.alpha.portlet.danh_muc.model.LoaiHoSo
 * @generated
 */
public abstract class LoaiHoSoBaseImpl extends LoaiHoSoModelImpl
	implements LoaiHoSo {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loai ho so model instance should use the {@link LoaiHoSo} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			LoaiHoSoLocalServiceUtil.addLoaiHoSo(this);
		}
		else {
			LoaiHoSoLocalServiceUtil.updateLoaiHoSo(this);
		}
	}
}