/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.dmdc.service.base;

import com.alpha.portlet.dmdc.model.BieuMauBaoCao;
import com.alpha.portlet.dmdc.service.BieuMauBaoCaoService;
import com.alpha.portlet.dmdc.service.persistence.BieuMauBaoCaoPersistence;
import com.alpha.portlet.dmdc.service.persistence.CauHinhPersistence;
import com.alpha.portlet.dmdc.service.persistence.FileDinhKemPersistence;
import com.alpha.portlet.dmdc.service.persistence.PhanQuyenFinder;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the bieu mau bao cao remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.alpha.portlet.dmdc.service.impl.BieuMauBaoCaoServiceImpl}.
 * </p>
 *
 * @author darkn
 * @see com.alpha.portlet.dmdc.service.impl.BieuMauBaoCaoServiceImpl
 * @see com.alpha.portlet.dmdc.service.BieuMauBaoCaoServiceUtil
 * @generated
 */
public abstract class BieuMauBaoCaoServiceBaseImpl extends BaseServiceImpl
	implements BieuMauBaoCaoService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.alpha.portlet.dmdc.service.BieuMauBaoCaoServiceUtil} to access the bieu mau bao cao remote service.
	 */

	/**
	 * Returns the bieu mau bao cao local service.
	 *
	 * @return the bieu mau bao cao local service
	 */
	public com.alpha.portlet.dmdc.service.BieuMauBaoCaoLocalService getBieuMauBaoCaoLocalService() {
		return bieuMauBaoCaoLocalService;
	}

	/**
	 * Sets the bieu mau bao cao local service.
	 *
	 * @param bieuMauBaoCaoLocalService the bieu mau bao cao local service
	 */
	public void setBieuMauBaoCaoLocalService(
		com.alpha.portlet.dmdc.service.BieuMauBaoCaoLocalService bieuMauBaoCaoLocalService) {
		this.bieuMauBaoCaoLocalService = bieuMauBaoCaoLocalService;
	}

	/**
	 * Returns the bieu mau bao cao remote service.
	 *
	 * @return the bieu mau bao cao remote service
	 */
	public com.alpha.portlet.dmdc.service.BieuMauBaoCaoService getBieuMauBaoCaoService() {
		return bieuMauBaoCaoService;
	}

	/**
	 * Sets the bieu mau bao cao remote service.
	 *
	 * @param bieuMauBaoCaoService the bieu mau bao cao remote service
	 */
	public void setBieuMauBaoCaoService(
		com.alpha.portlet.dmdc.service.BieuMauBaoCaoService bieuMauBaoCaoService) {
		this.bieuMauBaoCaoService = bieuMauBaoCaoService;
	}

	/**
	 * Returns the bieu mau bao cao persistence.
	 *
	 * @return the bieu mau bao cao persistence
	 */
	public BieuMauBaoCaoPersistence getBieuMauBaoCaoPersistence() {
		return bieuMauBaoCaoPersistence;
	}

	/**
	 * Sets the bieu mau bao cao persistence.
	 *
	 * @param bieuMauBaoCaoPersistence the bieu mau bao cao persistence
	 */
	public void setBieuMauBaoCaoPersistence(
		BieuMauBaoCaoPersistence bieuMauBaoCaoPersistence) {
		this.bieuMauBaoCaoPersistence = bieuMauBaoCaoPersistence;
	}

	/**
	 * Returns the cau hinh local service.
	 *
	 * @return the cau hinh local service
	 */
	public com.alpha.portlet.dmdc.service.CauHinhLocalService getCauHinhLocalService() {
		return cauHinhLocalService;
	}

	/**
	 * Sets the cau hinh local service.
	 *
	 * @param cauHinhLocalService the cau hinh local service
	 */
	public void setCauHinhLocalService(
		com.alpha.portlet.dmdc.service.CauHinhLocalService cauHinhLocalService) {
		this.cauHinhLocalService = cauHinhLocalService;
	}

	/**
	 * Returns the cau hinh remote service.
	 *
	 * @return the cau hinh remote service
	 */
	public com.alpha.portlet.dmdc.service.CauHinhService getCauHinhService() {
		return cauHinhService;
	}

	/**
	 * Sets the cau hinh remote service.
	 *
	 * @param cauHinhService the cau hinh remote service
	 */
	public void setCauHinhService(
		com.alpha.portlet.dmdc.service.CauHinhService cauHinhService) {
		this.cauHinhService = cauHinhService;
	}

	/**
	 * Returns the cau hinh persistence.
	 *
	 * @return the cau hinh persistence
	 */
	public CauHinhPersistence getCauHinhPersistence() {
		return cauHinhPersistence;
	}

	/**
	 * Sets the cau hinh persistence.
	 *
	 * @param cauHinhPersistence the cau hinh persistence
	 */
	public void setCauHinhPersistence(CauHinhPersistence cauHinhPersistence) {
		this.cauHinhPersistence = cauHinhPersistence;
	}

	/**
	 * Returns the file dinh kem local service.
	 *
	 * @return the file dinh kem local service
	 */
	public com.alpha.portlet.dmdc.service.FileDinhKemLocalService getFileDinhKemLocalService() {
		return fileDinhKemLocalService;
	}

	/**
	 * Sets the file dinh kem local service.
	 *
	 * @param fileDinhKemLocalService the file dinh kem local service
	 */
	public void setFileDinhKemLocalService(
		com.alpha.portlet.dmdc.service.FileDinhKemLocalService fileDinhKemLocalService) {
		this.fileDinhKemLocalService = fileDinhKemLocalService;
	}

	/**
	 * Returns the file dinh kem remote service.
	 *
	 * @return the file dinh kem remote service
	 */
	public com.alpha.portlet.dmdc.service.FileDinhKemService getFileDinhKemService() {
		return fileDinhKemService;
	}

	/**
	 * Sets the file dinh kem remote service.
	 *
	 * @param fileDinhKemService the file dinh kem remote service
	 */
	public void setFileDinhKemService(
		com.alpha.portlet.dmdc.service.FileDinhKemService fileDinhKemService) {
		this.fileDinhKemService = fileDinhKemService;
	}

	/**
	 * Returns the file dinh kem persistence.
	 *
	 * @return the file dinh kem persistence
	 */
	public FileDinhKemPersistence getFileDinhKemPersistence() {
		return fileDinhKemPersistence;
	}

	/**
	 * Sets the file dinh kem persistence.
	 *
	 * @param fileDinhKemPersistence the file dinh kem persistence
	 */
	public void setFileDinhKemPersistence(
		FileDinhKemPersistence fileDinhKemPersistence) {
		this.fileDinhKemPersistence = fileDinhKemPersistence;
	}

	/**
	 * Returns the phan quyen local service.
	 *
	 * @return the phan quyen local service
	 */
	public com.alpha.portlet.dmdc.service.PhanQuyenLocalService getPhanQuyenLocalService() {
		return phanQuyenLocalService;
	}

	/**
	 * Sets the phan quyen local service.
	 *
	 * @param phanQuyenLocalService the phan quyen local service
	 */
	public void setPhanQuyenLocalService(
		com.alpha.portlet.dmdc.service.PhanQuyenLocalService phanQuyenLocalService) {
		this.phanQuyenLocalService = phanQuyenLocalService;
	}

	/**
	 * Returns the phan quyen remote service.
	 *
	 * @return the phan quyen remote service
	 */
	public com.alpha.portlet.dmdc.service.PhanQuyenService getPhanQuyenService() {
		return phanQuyenService;
	}

	/**
	 * Sets the phan quyen remote service.
	 *
	 * @param phanQuyenService the phan quyen remote service
	 */
	public void setPhanQuyenService(
		com.alpha.portlet.dmdc.service.PhanQuyenService phanQuyenService) {
		this.phanQuyenService = phanQuyenService;
	}

	/**
	 * Returns the phan quyen finder.
	 *
	 * @return the phan quyen finder
	 */
	public PhanQuyenFinder getPhanQuyenFinder() {
		return phanQuyenFinder;
	}

	/**
	 * Sets the phan quyen finder.
	 *
	 * @param phanQuyenFinder the phan quyen finder
	 */
	public void setPhanQuyenFinder(PhanQuyenFinder phanQuyenFinder) {
		this.phanQuyenFinder = phanQuyenFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return BieuMauBaoCao.class;
	}

	protected String getModelClassName() {
		return BieuMauBaoCao.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = bieuMauBaoCaoPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.alpha.portlet.dmdc.service.BieuMauBaoCaoLocalService.class)
	protected com.alpha.portlet.dmdc.service.BieuMauBaoCaoLocalService bieuMauBaoCaoLocalService;
	@BeanReference(type = com.alpha.portlet.dmdc.service.BieuMauBaoCaoService.class)
	protected com.alpha.portlet.dmdc.service.BieuMauBaoCaoService bieuMauBaoCaoService;
	@BeanReference(type = BieuMauBaoCaoPersistence.class)
	protected BieuMauBaoCaoPersistence bieuMauBaoCaoPersistence;
	@BeanReference(type = com.alpha.portlet.dmdc.service.CauHinhLocalService.class)
	protected com.alpha.portlet.dmdc.service.CauHinhLocalService cauHinhLocalService;
	@BeanReference(type = com.alpha.portlet.dmdc.service.CauHinhService.class)
	protected com.alpha.portlet.dmdc.service.CauHinhService cauHinhService;
	@BeanReference(type = CauHinhPersistence.class)
	protected CauHinhPersistence cauHinhPersistence;
	@BeanReference(type = com.alpha.portlet.dmdc.service.FileDinhKemLocalService.class)
	protected com.alpha.portlet.dmdc.service.FileDinhKemLocalService fileDinhKemLocalService;
	@BeanReference(type = com.alpha.portlet.dmdc.service.FileDinhKemService.class)
	protected com.alpha.portlet.dmdc.service.FileDinhKemService fileDinhKemService;
	@BeanReference(type = FileDinhKemPersistence.class)
	protected FileDinhKemPersistence fileDinhKemPersistence;
	@BeanReference(type = com.alpha.portlet.dmdc.service.PhanQuyenLocalService.class)
	protected com.alpha.portlet.dmdc.service.PhanQuyenLocalService phanQuyenLocalService;
	@BeanReference(type = com.alpha.portlet.dmdc.service.PhanQuyenService.class)
	protected com.alpha.portlet.dmdc.service.PhanQuyenService phanQuyenService;
	@BeanReference(type = PhanQuyenFinder.class)
	protected PhanQuyenFinder phanQuyenFinder;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private BieuMauBaoCaoServiceClpInvoker _clpInvoker = new BieuMauBaoCaoServiceClpInvoker();
}