/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.dmdc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BieuMauBaoCao service. Represents a row in the &quot;alpha_dm_bieumaubaocao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alpha.portlet.dmdc.model.impl.BieuMauBaoCaoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alpha.portlet.dmdc.model.impl.BieuMauBaoCaoImpl}.
 * </p>
 *
 * @author darkn
 * @see BieuMauBaoCao
 * @see com.alpha.portlet.dmdc.model.impl.BieuMauBaoCaoImpl
 * @see com.alpha.portlet.dmdc.model.impl.BieuMauBaoCaoModelImpl
 * @generated
 */
public interface BieuMauBaoCaoModel extends BaseModel<BieuMauBaoCao>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bieu mau bao cao model instance should use the {@link BieuMauBaoCao} interface instead.
	 */

	/**
	 * Returns the primary key of this bieu mau bao cao.
	 *
	 * @return the primary key of this bieu mau bao cao
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bieu mau bao cao.
	 *
	 * @param primaryKey the primary key of this bieu mau bao cao
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bieu mau bao cao ID of this bieu mau bao cao.
	 *
	 * @return the bieu mau bao cao ID of this bieu mau bao cao
	 */
	public long getBieuMauBaoCaoId();

	/**
	 * Sets the bieu mau bao cao ID of this bieu mau bao cao.
	 *
	 * @param bieuMauBaoCaoId the bieu mau bao cao ID of this bieu mau bao cao
	 */
	public void setBieuMauBaoCaoId(long bieuMauBaoCaoId);

	/**
	 * Returns the group ID of this bieu mau bao cao.
	 *
	 * @return the group ID of this bieu mau bao cao
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this bieu mau bao cao.
	 *
	 * @param groupId the group ID of this bieu mau bao cao
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this bieu mau bao cao.
	 *
	 * @return the company ID of this bieu mau bao cao
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bieu mau bao cao.
	 *
	 * @param companyId the company ID of this bieu mau bao cao
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bieu mau bao cao.
	 *
	 * @return the user ID of this bieu mau bao cao
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bieu mau bao cao.
	 *
	 * @param userId the user ID of this bieu mau bao cao
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bieu mau bao cao.
	 *
	 * @return the user uuid of this bieu mau bao cao
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this bieu mau bao cao.
	 *
	 * @param userUuid the user uuid of this bieu mau bao cao
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bieu mau bao cao.
	 *
	 * @return the user name of this bieu mau bao cao
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bieu mau bao cao.
	 *
	 * @param userName the user name of this bieu mau bao cao
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bieu mau bao cao.
	 *
	 * @return the create date of this bieu mau bao cao
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bieu mau bao cao.
	 *
	 * @param createDate the create date of this bieu mau bao cao
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bieu mau bao cao.
	 *
	 * @return the modified date of this bieu mau bao cao
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bieu mau bao cao.
	 *
	 * @param modifiedDate the modified date of this bieu mau bao cao
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the chuyen muc bieu mau ID of this bieu mau bao cao.
	 *
	 * @return the chuyen muc bieu mau ID of this bieu mau bao cao
	 */
	public long getChuyenMucBieuMauId();

	/**
	 * Sets the chuyen muc bieu mau ID of this bieu mau bao cao.
	 *
	 * @param chuyenMucBieuMauId the chuyen muc bieu mau ID of this bieu mau bao cao
	 */
	public void setChuyenMucBieuMauId(long chuyenMucBieuMauId);

	/**
	 * Returns the ten of this bieu mau bao cao.
	 *
	 * @return the ten of this bieu mau bao cao
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this bieu mau bao cao.
	 *
	 * @param ten the ten of this bieu mau bao cao
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma of this bieu mau bao cao.
	 *
	 * @return the ma of this bieu mau bao cao
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this bieu mau bao cao.
	 *
	 * @param ma the ma of this bieu mau bao cao
	 */
	public void setMa(String ma);

	/**
	 * Returns the mo ta of this bieu mau bao cao.
	 *
	 * @return the mo ta of this bieu mau bao cao
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this bieu mau bao cao.
	 *
	 * @param moTa the mo ta of this bieu mau bao cao
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the loai of this bieu mau bao cao.
	 *
	 * @return the loai of this bieu mau bao cao
	 */
	public int getLoai();

	/**
	 * Sets the loai of this bieu mau bao cao.
	 *
	 * @param loai the loai of this bieu mau bao cao
	 */
	public void setLoai(int loai);

	/**
	 * Returns the hoat dong of this bieu mau bao cao.
	 *
	 * @return the hoat dong of this bieu mau bao cao
	 */
	public boolean getHoatDong();

	/**
	 * Returns <code>true</code> if this bieu mau bao cao is hoat dong.
	 *
	 * @return <code>true</code> if this bieu mau bao cao is hoat dong; <code>false</code> otherwise
	 */
	public boolean isHoatDong();

	/**
	 * Sets whether this bieu mau bao cao is hoat dong.
	 *
	 * @param hoatDong the hoat dong of this bieu mau bao cao
	 */
	public void setHoatDong(boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.alpha.portlet.dmdc.model.BieuMauBaoCao bieuMauBaoCao);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alpha.portlet.dmdc.model.BieuMauBaoCao> toCacheModel();

	@Override
	public com.alpha.portlet.dmdc.model.BieuMauBaoCao toEscapedModel();

	@Override
	public com.alpha.portlet.dmdc.model.BieuMauBaoCao toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}