/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alpha.portlet.dmdc.model;

import com.alpha.portlet.dmdc.service.persistence.FileDinhKemPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FileDinhKem service. Represents a row in the &quot;alpha_dm_filedinhkem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alpha.portlet.dmdc.model.impl.FileDinhKemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alpha.portlet.dmdc.model.impl.FileDinhKemImpl}.
 * </p>
 *
 * @author darkn
 * @see FileDinhKem
 * @see com.alpha.portlet.dmdc.model.impl.FileDinhKemImpl
 * @see com.alpha.portlet.dmdc.model.impl.FileDinhKemModelImpl
 * @generated
 */
public interface FileDinhKemModel extends BaseModel<FileDinhKem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file dinh kem model instance should use the {@link FileDinhKem} interface instead.
	 */

	/**
	 * Returns the primary key of this file dinh kem.
	 *
	 * @return the primary key of this file dinh kem
	 */
	public FileDinhKemPK getPrimaryKey();

	/**
	 * Sets the primary key of this file dinh kem.
	 *
	 * @param primaryKey the primary key of this file dinh kem
	 */
	public void setPrimaryKey(FileDinhKemPK primaryKey);

	/**
	 * Returns the resource code of this file dinh kem.
	 *
	 * @return the resource code of this file dinh kem
	 */
	public long getResourceCode();

	/**
	 * Sets the resource code of this file dinh kem.
	 *
	 * @param resourceCode the resource code of this file dinh kem
	 */
	public void setResourceCode(long resourceCode);

	/**
	 * Returns the prim key of this file dinh kem.
	 *
	 * @return the prim key of this file dinh kem
	 */
	public long getPrimKey();

	/**
	 * Sets the prim key of this file dinh kem.
	 *
	 * @param primKey the prim key of this file dinh kem
	 */
	public void setPrimKey(long primKey);

	/**
	 * Returns the file entry ID of this file dinh kem.
	 *
	 * @return the file entry ID of this file dinh kem
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this file dinh kem.
	 *
	 * @param fileEntryId the file entry ID of this file dinh kem
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the nhan qua mang of this file dinh kem.
	 *
	 * @return the nhan qua mang of this file dinh kem
	 */
	public boolean getNhanQuaMang();

	/**
	 * Returns <code>true</code> if this file dinh kem is nhan qua mang.
	 *
	 * @return <code>true</code> if this file dinh kem is nhan qua mang; <code>false</code> otherwise
	 */
	public boolean isNhanQuaMang();

	/**
	 * Sets whether this file dinh kem is nhan qua mang.
	 *
	 * @param nhanQuaMang the nhan qua mang of this file dinh kem
	 */
	public void setNhanQuaMang(boolean nhanQuaMang);

	/**
	 * Returns the extension of this file dinh kem.
	 *
	 * @return the extension of this file dinh kem
	 */
	@AutoEscape
	public String getExtension();

	/**
	 * Sets the extension of this file dinh kem.
	 *
	 * @param extension the extension of this file dinh kem
	 */
	public void setExtension(String extension);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.alpha.portlet.dmdc.model.FileDinhKem fileDinhKem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alpha.portlet.dmdc.model.FileDinhKem> toCacheModel();

	@Override
	public com.alpha.portlet.dmdc.model.FileDinhKem toEscapedModel();

	@Override
	public com.alpha.portlet.dmdc.model.FileDinhKem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}